name: gitpod-demo
recipe: pantheon
config:
  framework: drupal8
  site: gitpod-demo
  id: 67d60aa1-3bb5-4127-b0cb-dfe0fef0b09f

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/pantheon": ./../../
